### ISSUE TITLE
Cue point breaks app

### ISSUE THREAD

**Issue by infojunkie** [versioduo/edit#1]
When I load [this file](https://github.com/versioduo/edit/files/8317976/26-2.zip) into the Editor app, I see a JS error
```
Uncaught ReferenceError: vents is not defined
    at V2EditorTrack.#addDetails (V2EditorTrack.js:406:30)
    at new V2EditorTrack (V2EditorTrack.js:62:21)
    at V2Editor.show (V2Editor.js:107:25)
    at V2Editor.#addFile (V2Editor.js:132:10)
    at FileReader.reader.onload (V2Editor.js:139:20)
```

**Comment by kaysievers** [comment]
Oh, there was an 'e' missing :)
      addDetail('Cue Point', vents.meta.cuePoint);

Thanks!

**Comment by infojunkie** [comment]
Thanks, works for me now. Fyi, the cue point shows as decimal digits, whereas their intent is clearly to be ASCII text, as per https://www.recordingblogs.com/wiki/midi-cue-point-meta-message. Happy to open a different issue if you would consider changing the display to text.

**Comment by kaysievers** [comment]
I see. I've added a call now to decode the text of the event.

**Comment by infojunkie** [comment]
Thank you! Love your web apps :heart_eyes:
